# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  name: HostedByMe

variables:
  imageName: '$(dockerId)/dockertest:$(build.buildId)'

steps:
- task: Docker@1
  displayName: Docker login
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'samekrille dockerhub'
    command: login
- script: docker build -t $(imageName)-test --target test .
  displayName: 'docker build to target test'
- script:  docker run --rm -v /var/dockershared/$(build.buildId):/TestResults/ $(imageName)-test
  displayName: 'run unit tests'
- task: PublishTestResults@2
  inputs:
    testRunner: 'VSTest'
    testResultsFiles: '/var/dockershared/$(build.buildId)/**/*.trx'
- script: docker build -t $(imageName) .
  displayName: 'docker build final'
- script: docker push $(imageName)
  displayName: 'docker push'
- task: HelmInstaller@0
  displayName: 'Install Helm 2.9.1'
- task: HelmDeploy@0
  displayName: 'helm package'
  inputs:
    command: package
    chartPath: DockerTest/charts/dockertest
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'