# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: '$(dockerId)/dockertest:$(build.buildId)'

steps:
- task: Docker@1
  displayName: Login
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'samekrille dockerhub'
    command: login
- script: docker build -f DockerTest/Dockerfile -t $(imageName)-test --target test .
  displayName: 'docker build for test'
- script: id=$(docker run -dit $(imageName)-test); docker cp $id:/src/Business.Test/TestResults/TestResult.trx $(System.DefaultWorkingDirectory)
  displayName: 'docker build and run test'
- task: PublishTestResults@2
  inputs:
    testRunner: 'NUnit'
    testResultsFiles: '**/*.trx' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional
- script: docker build -f DockerTest/Dockerfile -t $(imageName) .
  displayName: 'docker build final'
- script: docker push $(imageName)
  displayName: 'docker push'
- task: HelmInstaller@0
  displayName: 'Install Helm 2.9.1'
- task: HelmDeploy@0
  displayName: 'helm package'
  inputs:
    command: package
    chartPath: DockerTest/charts/dockertest
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'